apiVersion: v1
kind: Service
metadata:
  name: springboot
  namespace: springboot
  
  labels:
    app: springboot
spec:
  type: LoadBalancer
  selector:
    app: springboot
  ports:
  - name: springboot-port
    protocol: TCP
    port: 8086
    targetPort: 8086
    
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springboot
  namespace: springboot
  labels:
    app: springboot
spec:
  replicas: 2
  template:
    metadata:
      namespace: springboot
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: "traqtest/s01:latest"
        livenessProbe:
          tcpSocket:
            port: 8086
          initialDelaySeconds: 120
          periodSeconds: 5
        ports:
        - containerPort: 8086
        resources:
          requests:
            cpu: 400m
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi
